import { shortcutDefinitions } from "@app/shortcuts/shortcutRegistry";
import { getSettingsSections } from "@app/settings/settingsRegistry";
import { getSetting } from "@app/settings/settingsStore";
import { AUTOSAVE_INTERVAL_KEY, DEFAULT_AUTOSAVE_INTERVAL_MINUTES, saveAutosaveInterval } from "@app/save/SaveProvider";
import { useEffect, useState } from "react";
import { themeOptions } from "@app/theme/themes";
import { useTheme } from "@app/theme/ThemeProvider";
import type { AppearanceMode, ThemeId } from "@app/theme/types";
import "./SettingsPage.css";

export function SettingsPage(): JSX.Element {
  const { appearance, updateAppearance } = useTheme();
  const [interval, setInterval] = useState(DEFAULT_AUTOSAVE_INTERVAL_MINUTES);
  useEffect(() => { void getSetting(AUTOSAVE_INTERVAL_KEY, DEFAULT_AUTOSAVE_INTERVAL_MINUTES).then(setInterval); }, []);
  const updateInterval = (value: number): void => { const next = Math.min(60, Math.max(1, value || DEFAULT_AUTOSAVE_INTERVAL_MINUTES)); setInterval(next); void saveAutosaveInterval(next); };
  const selectTheme = (label: string, value: ThemeId, field: "manualTheme" | "dayTheme" | "nightTheme" | "systemLightTheme" | "systemDarkTheme"): JSX.Element => <label className="atlas-settings__field"><span>{label}</span><select value={value} onChange={(event) => updateAppearance({ [field]: event.target.value as ThemeId })}>{themeOptions.map((theme) => <option key={theme.id} value={theme.id}>{theme.name}</option>)}</select></label>;
  return <div className="atlas-settings"><h1>Settings</h1><section className="atlas-settings__section"><h2>Appearance</h2><p className="atlas-settings__muted">Choose how Atlas selects the workspace theme.</p><label className="atlas-settings__field"><span>Appearance mode</span><select value={appearance.mode} onChange={(event) => updateAppearance({ mode: event.target.value as AppearanceMode })}><option value="manual">Manual</option><option value="scheduled">Scheduled</option><option value="system">Follow System</option></select></label>{appearance.mode === "manual" && selectTheme("Theme", appearance.manualTheme, "manualTheme")}{appearance.mode === "scheduled" && <><p className="atlas-settings__muted">Atlas uses your computer’s local time and updates automatically.</p>{selectTheme("Daytime theme", appearance.dayTheme, "dayTheme")}{selectTheme("Nighttime theme", appearance.nightTheme, "nightTheme")}<label className="atlas-settings__field"><span>Nighttime begins</span><input type="time" value={appearance.nightStart} onChange={(event) => updateAppearance({ nightStart: event.target.value })} /></label><label className="atlas-settings__field"><span>Daytime begins</span><input type="time" value={appearance.dayStart} onChange={(event) => updateAppearance({ dayStart: event.target.value })} /></label><p className="atlas-settings__muted">When both times are the same, the daytime theme stays active all day.</p></>}{appearance.mode === "system" && <><p className="atlas-settings__muted">Atlas follows your operating system’s light or dark appearance preference.</p>{selectTheme("System light theme", appearance.systemLightTheme, "systemLightTheme")}{selectTheme("System dark theme", appearance.systemDarkTheme, "systemDarkTheme")}</>}</section><section className="atlas-settings__section"><h2>Autosave</h2><p className="atlas-settings__muted">Atlas saves the open asset periodically and once more before closing.</p><label className="atlas-settings__field"><span>Autosave interval (minutes)</span><input type="number" min="1" max="60" value={interval} onChange={(event) => updateInterval(Number(event.target.value))} /></label></section><section className="atlas-settings__section"><h2>Keyboard Shortcuts</h2><p className="atlas-settings__muted">Available throughout Atlas. Shortcuts are disabled while typing unless they are editing actions.</p><dl className="atlas-settings__shortcuts">{shortcutDefinitions.map((shortcut) => <div key={shortcut.id}><dt>{shortcut.label}</dt><dd>{shortcut.keys}</dd></div>)}</dl></section>{getSettingsSections().map(({ id, label, component: Section }) => <section className="atlas-settings__section" key={id}><h2>{label}</h2><Section /></section>)}</div>;
}
